# cmake/platform_check.cmake — Build-time enforcement that core/ contains no OS-specific calls.
#
# Strategy: a custom CMake target runs grep over every .cpp/.h file under core/.
# The deny-list matches exact function call patterns that indicate direct OS API usage.
# Any match causes the build to fail with a descriptive error.

cmake_minimum_required(VERSION 3.25)

# ---------------------------------------------------------------------------
# Deny-list of OS-specific call patterns
# Each entry is a grep-compatible extended-regex fragment.
# Patterns match bare function calls (not C++ member calls with . or ->).
# We use negative lookbehind alternative: (^|[^a-zA-Z0-9_.->]) before function name.
# Note: > is included to avoid matching after -> 
# ---------------------------------------------------------------------------
set(MALIBU_OS_DENY_LIST
    # POSIX: open(path, flags, ...) - bare function call
    "(^|[^a-zA-Z0-9_.->])\\bopen\\s*\\([^)]*\\)\\s*[;,)]"
    # POSIX: read(fd, buf, count) - bare function call
    "(^|[^a-zA-Z0-9_.->])\\bread\\s*\\([^)]*\\)\\s*[;,)]"
    # POSIX: write(fd, buf, count) - bare function call
    "(^|[^a-zA-Z0-9_.->])\\bwrite\\s*\\([^)]*\\)\\s*[;,)]"
    # POSIX: close(fd) - bare function call
    "(^|[^a-zA-Z0-9_.->])\\bclose\\s*\\([^)]*\\)\\s*[;,)]"
    # POSIX: socket(domain, type, protocol)
    "(^|[^a-zA-Z0-9_.->])\\bsocket\\s*\\([^)]*\\)\\s*[;,)]"
    # POSIX: connect(sockfd, addr, addrlen)
    "(^|[^a-zA-Z0-9_.->])\\bconnect\\s*\\([^)]*\\)\\s*[;,)]"
    # POSIX: mmap(addr, len, prot, flags, fd, offset)
    "(^|[^a-zA-Z0-9_.->])\\bmmap\\s*\\([^)]*\\)\\s*[;,)]"
    # POSIX: munmap(addr, len)
    "(^|[^a-zA-Z0-9_.->])\\bmunmap\\s*\\([^)]*\\)\\s*[;,)]"
    # Win32: CreateFile/W/A - bare function call
    "(^|[^a-zA-Z0-9_.->])\\bCreateFile[WA]?\\s*\\([^)]*\\)\\s*[;,)]"
    # Win32: ReadFile/WriteFile - bare function call
    "(^|[^a-zA-Z0-9_.->])\\bReadFile\\s*\\([^)]*\\)\\s*[;,)]"
    "(^|[^a-zA-Z0-9_.->])\\bWriteFile\\s*\\([^)]*\\)\\s*[;,)]"
    # Win32: VirtualAlloc/VirtualFree - bare function call
    "(^|[^a-zA-Z0-9_.->])\\bVirtualAlloc\\s*\\([^)]*\\)\\s*[;,)]"
    "(^|[^a-zA-Z0-9_.->])\\bVirtualFree\\s*\\([^)]*\\)\\s*[;,)]"
    # Wayland: wl_display_connect(name)
    "(^|[^a-zA-Z0-9_.->])\\bwl_display_connect\\s*\\([^)]*\\)\\s*[;,)]"
    # X11: xcb_connect(displayname, screen)
    "(^|[^a-zA-Z0-9_.->])\\bxcb_connect\\s*\\([^)]*\\)\\s*[;,)]"
)

# Build a single alternation regex for grep -E
string(JOIN "|" MALIBU_OS_DENY_REGEX ${MALIBU_OS_DENY_LIST})

# Path to the core source tree (evaluated at generate time; used in the script below)
set(MALIBU_CORE_SRC_DIR "${CMAKE_SOURCE_DIR}/core")

# ---------------------------------------------------------------------------
# Generate a small shell script that performs the check.
# We write it to the build directory so it is always up-to-date.
# ---------------------------------------------------------------------------
set(_CHECK_SCRIPT "${CMAKE_BINARY_DIR}/cmake_scripts/check_core_os_calls.sh")

file(WRITE "${_CHECK_SCRIPT}"
"#!/usr/bin/env bash
# Auto-generated by platform_check.cmake — do not edit.
set -euo pipefail

CORE_DIR=\"${MALIBU_CORE_SRC_DIR}\"
DENY_REGEX=\"${MALIBU_OS_DENY_REGEX}\"

if ! command -v grep >/dev/null 2>&1; then
    echo '[platform_check] ERROR: grep not found in PATH.' >&2
    exit 1
fi

# Find all C/C++ source and header files under core/
mapfile -t FILES < <(find \"\$CORE_DIR\" \\( -name '*.cpp' -o -name '*.h' -o -name '*.hpp' -o -name '*.cc' \\) -type f 2>/dev/null || true)

if [ \${#FILES[@]} -eq 0 ]; then
    echo '[platform_check] No source files found under core/ — skipping OS call check.'
    exit 0
fi

# Regex to detect declarations (return type before function name)
# Matches: 'type name(', 'virtual type name(', 'static type name(', 'inline type name('
DECL_REGEX='(^|[[:space:]])(virtual[[:space:]]+)?(static[[:space:]]+)?(inline[[:space:]]+)?(const[[:space:]]+)?(bool|void|int|long|short|char|float|double|auto|size_t|ssize_t|uint8_t|uint16_t|uint32_t|uint64_t|int8_t|int16_t|int32_t|int64_t|std::[a-zA-Z_][a-zA-Z0-9_]*|[a-zA-Z_][a-zA-Z0-9_]*\\s*::\\s*[a-zA-Z_][a-zA-Z0-9_]*)[[:space:]]+[a-zA-Z_][a-zA-Z0-9_]*\\s*\\('

FOUND=0
for F in \"\${FILES[@]}\"; do
    # Skip files inside platform/ subdirectories that happen to be under core/ (shouldn't exist, but be safe)
    MATCHES=\$(grep -En \"\$DENY_REGEX\" \"\$F\" 2>/dev/null || true)
    if [ -n \"\$MATCHES\" ]; then
        # Filter out false positives: declarations
        FILTERED=\$(echo \"\$MATCHES\" | grep -Ev \"\$DECL_REGEX\" || true)
        if [ -n \"\$FILTERED\" ]; then
            echo \"[platform_check] FORBIDDEN OS call in core file: \$F\" >&2
            echo \"\$FILTERED\" | while IFS= read -r LINE; do
                echo \"  \$LINE\" >&2
            done
            FOUND=1
        fi
    fi
done

if [ \$FOUND -ne 0 ]; then
    echo '' >&2
    echo '[platform_check] FAIL: core/ files must not call OS-specific APIs directly.' >&2
    echo '[platform_check] Move all OS calls to platform/ backend implementations.' >&2
    exit 1
fi

echo '[platform_check] PASS: no forbidden OS calls found in core/.'
exit 0
")

execute_process(COMMAND chmod +x "${_CHECK_SCRIPT}")

# ---------------------------------------------------------------------------
# Custom target: check_core_os_calls
# Runs automatically as part of the ALL target so CI catches violations.
# ---------------------------------------------------------------------------
add_custom_target(check_core_os_calls ALL
    COMMAND bash "${_CHECK_SCRIPT}"
    COMMENT "Checking core/ for forbidden OS-specific API calls..."
    VERBATIM
)

# ---------------------------------------------------------------------------
# clang-tidy configuration helper
# If clang-tidy is available we also wire it up per-target.
# Call malibu_apply_clang_tidy(target) from the root CMakeLists.txt.
# ---------------------------------------------------------------------------
find_program(CLANG_TIDY_EXE NAMES clang-tidy clang-tidy-17 clang-tidy-16 clang-tidy-15)

function(malibu_apply_clang_tidy target)
    if(CLANG_TIDY_EXE)
        set_target_properties("${target}" PROPERTIES
            CXX_CLANG_TIDY "${CLANG_TIDY_EXE};--config-file=${CMAKE_SOURCE_DIR}/.clang-tidy"
        )
        message(STATUS "clang-tidy enabled for target: ${target}")
    else()
        message(STATUS "clang-tidy not found; skipping for target: ${target}")
    endif()
endfunction()
